export default {
  s3_url: "https://art.masterbrews.cards/artists/",
  artists: [
  {
    name: "PLS&TY",
    username: "PLS&TY",
    s3_folder: "pls&ty/",
    img_qty: "5",
    img_ext: "jpg",
    countryCode: "mexico",
    links: [{
      web: "http://www.plsandty.com",
      twitter: "https://www.twitter.com/plsandtybased",
      ig: "https://www.instagram.com/plsandty",
      fb: "https://www.facebook.com/plsandty",
      superare: "https://www.superrare.co/plsandty",
      
    },],
    titles: [{
      1: "1",
      2: "2",
      3: "3",
      4: "4",
      5: "5",
  
    }],
    bio:
      "Tommy Leas, a Florida native - better known as PLS&TY - is burgeoning into the electronic dance music scene with his unique sound: languid bass, captivating vocals and enough upbeat melodies to make anybody feel good. He is best known for his collection of chart topping singles including \"Good Vibes\", \"Down For Me\", \"Rebel Love\", and \"Motives\".",
  },
  {
    name: "Larienne Chan",
    username: "Larienne Chan",
    s3_folder: "chan/",
    img_qty: "4",
    img_ext: "jpg",
    countryCode: "japan",
    links: [{
      ig: "https://www.instagram.com/lariennechan/",
      fb: "https://facebook.com/lariennechan/",
      foundation: "https://foundation.app/Larienne",
      makers: "https://makersplace.com/larienne/",
      hicetnunc: "https://www.hicetnunc.xyz/tz/tz1R42md7gBUkKYJVpVNDfqDjnd1yrTZzuvh",      
    },],
    titles: [{
      1: "Late for Music Class",
      2: "True Self",
      3: "Loss",
      4: "Drive",
    }],
    bio:
      "Larienne is a freelance artist from Finland who loves melancholic, nostalgic retro art as well as witches and spooky stuff. She has worked for such companies as Blizzard and Volition.",
  },
  {
    name: "Sebas Theriault",
    username: "Sebas Theriault",
    s3_folder: "sebas/",
    img_qty: "8",
    img_ext: "png",
    countryCode: "canada",
    links: [{
      web: "http://www.steriodesign.com/",
      fb: "http://www.facebook.com/steriodesign",
      ig: "http://www.instagram.com/steriodesign",
    },],
    titles: [{
      1: "The Evil Dead",
      2: "Bubbles Want Kitties",
      3: "Chaser Dreamers",
      4: "Danny Trejo",
      5: "Joe Dante Screening",
      6: "Lagwagon Tony Hawk",
      7: "Mute the Raven",
      8: "Nuclear No Emotion",
    }],
    bio:
      "Sebas Theriault is a french Canadian / Acadian graphic designer & Illustrator located in Moncton, New Brunswick, Canada. A huge fan of pop culture, he basically lives in his own wannabe movie memorabilia museum and is frequently getting to work with many of his childhood idols from the music and movie industry.",
  },
  {
    name: "Mark McKenna",
    username: "Mark McKenna",
    s3_folder: "mckenna/",
    img_qty: "12",
    img_ext: "jpg",
    countryCode: "united states",
    links: [{
      web: "https://www.markmckennaart.com/",
      web2: "https://combatjacks.com/",
      web3: "https://bananatail.com/",
      twitter: "https://twitter.com/MarkMcKenna419",
      ig: "https://www.instagram.com/mckinks1/?hl=en",
      fb: "https://www.facebook.com/Mark-Mckenna-Art-708923312493524/",
    },],
    titles: [{
      1: "Boba Fett - Red",
      2: "Combat Jacks #4: The Finale",
      3: "Adam Warlock",
      4: "Batman vs. Hulk",
      5: "Batgirl vs",
      6: "TMNT B&W",
      7: "X-Force",
      8: "Deadpool",
      9: "Power Rangers",
      10: "Zatanna",
      11: "Combat Jacks: Headless",
      12: "Rockateer",   
    }],
    bio:
      "Mark McKenna, 35 year veteran of the comic book industry, has worked on Batman, Wolverine, Iron Man, The Hulk and more recently on Star Wars, counting close to 1000 credits in all. In 2012 his work on the online web comic titled “Star Wars: Blood of the Empire“ was collected into an 84 page trade paperback and was the lynchpin for the 2012 released Bio-ware online video game, The Old Republic.",
  },
  {
    name: "Ordo",
    username: "Ordo",
    s3_folder: "ordo/",
    img_qty: "5",
    img_ext: "png",
    countryCode: "portugal",
    links: [{
      web: "https://ordouniverse.com/",
      twitter: "https://twitter.com/OrdoUniverse",
      hicetnunc: "https://www.hicetnunc.xyz/tz/tz1PW1oWpqv1x63qZgo2kmYXP1zLRFtXSzJH",

    },],
    titles: [{
      1: "1",
      2: "2",
      3: "3",
      4: "4",
      5: "5",

    }],
    bio:
      "MM has been focusing on Abstract/Psychedelic art for over a decade. He is the founder of ORDO. A personal project that seeks to merge the blockchain world with the art world.",
  },
  {
    name: "Santiago Uceda",
    username: "Santiago Uceda",
    s3_folder: "uceda/",
    img_qty: "11",
    img_ext: "jpg",
    countryCode: "peru",
    links: [{
      web: "https://santiagouceda.com/",
      twitter: "https://twitter.com/SantiagoUceda",
      ig: "https://www.instagram.com/suceda/",
      foundation: "https://foundation.app/santiagouceda",
      hicetnunc: "https://t.co/WOOAEFJvnn?amp=1",
      showtime: "https://t.co/acyWTHRJIK?amp=1",
    },],
    titles: [{
      1: "Mothman",
      2: "Ahuizotl",
      3: "Red Dragon",
      4: "Sea Serpernt",
      5: "Robocall",
      6: "Crypto",
      7: "Dracula",
      8: "Fascist Rhino",
      9: "Texas",
      10: "Oregon",
      11: "Montana"
    }],
    bio:
      "Santiago Uceda is an illustrator and motion designer whose work has been recognized by American Illustration, Latin American Illustración & International Motion Arts Awards. Born in Lima, Peru, his work is influenced by peruvian culture, and the vibe and natural beauty of the Pacific Northwest where he lives now. His work has appeared in magazines, posters, apparel, murals, and animations.",
  },
  {
    name: "Adu",
    username: "Adu",
    s3_folder: "adu/",
    img_qty: "9",
    img_ext: "jpg",
    countryCode: "australia",
    links: [{
      ig: "https://www.instagram.com/ArtByAdu/",
      fb: "https://www.facebook.com/ArtByAdu/",
    },],
    titles: [{
      1: "Cera",
      2: "Bunquats",
      3: "Deck",
      4: "Domu",
      5: "Ekal'esh",
      6: "Gleps",
      7: "Sybeec",
      8: "Tauhm",
      9: "The Boy Who Cried",      
    }],
    bio:
      "Adu is an earthbound being, with a long and blurred history in the creative world. He currently finds himself working as a freelance full-time human. He enjoys long walks on the beach, laughing at fish (what's up with those legs?), and yelling at the waves (they're smug). Other times he toils away, magicking his brain-thoughts to life in the form of visual art.",
    },
    {
    name: "John Snow",
    username: "John Snow",
    s3_folder: "johnsnow/",
    img_qty: "4",
    img_ext: "png",
    countryCode: "denmark",
    links: [{
      opensea: "https://opensea.io/collection/99-guitar-pics",
      twitter: "https://twitter.com/CancerFzckinsux",
      ig: "https://www.instagram.com/99guitarpics/",
      rarible: "https://rarible.com/cancersucks",
      hicetnunc: "http://hen.link/cancersucks",
      
    },],
    titles: [{
      1: "Kiss",
      2: "Tapeworm",
      3: "Beatle",
      4: "Wu Tang",
     
    }],
    bio:
      "John Snow is a lifelong artist working in Digital Illustration, Animation, and 3d. He is a loving father and husband. The last year he has been working out of a hospital room where his daughter Fiona is receiving treatment for neuroblastoma. His artwork aims to bring a light hearted positivity to the world as well as bring attention to childhood cancers.",
    },
    {
    name: "Stefan Große Halbuer",
    username: "Stefan Große Halbuer",
    s3_folder: "stefan/",
    img_qty: "8",
    img_ext: "jpg",
    countryCode: "germany",
    links: [{
      web: "https://www.grossehalbuer.com",
      superare: "https://superrare.co/grossehalbuer",
      twitter: "https://twitter.com/grossehalbuer",
      ig: "https://instagram.com/plastic.pen",
      rarible: "https://rarible.com/grossehalbuer",
      foundation: "https://foundation.app/grossehalbuer",
      
    },],
    titles: [{
      1: "Daily Soup",
      2: "Escape from Reality",
      3: "Pinkie",
      4: "Radio",
      5: "Rainy Monday",
      6: "Robot's Journey",
      7: "Special Treat",
      8: "Suburb Sunday",
     
    }],
    bio:
      "Stefan Große Halbuer is a graphic designer and digital artist from Münster, Germany. He has been working as a freelancer for international corporations, NGOs and magazines as well as for musicians and startups, for almost 10 years. Stefan likes to play with details, experiment with perspectives and develop strong color palettes.",
    },
    {
    name: "John Kelly",
    username: "John Kelly",
    s3_folder: "jk/",
    img_qty: "12",
    img_ext: "png",
    countryCode: "scotland",
    links: [{
      web: "http://www.whitewyrmstudio.com/home/",
      ig: "https://www.instagram.com/white_wyrm_studio/",
    },],
    titles: [{
      1: "Joker",
      2: "Clarence",
      3: "Tea Time",
      4: "Rebel Princess",
      5: "Cute Killer",
      6: "Peace",
      7: "Lair",
      8: "Pete",
      9: "Captain Chaste",
      10: "Galbormort",
      11: "Cashing Out",
      12: "White Wyrm"
    }],
    bio:
      "According to his father, John Kelly was found under a gooseberry bush.  It would explain the affinity to fairies, the love of nature, and the smells…  Like most boys, John started off drawing tanks and warplanes, but his mother didn’t approve, so he tried dragons--that stuck.",
    },
    {
    name: "Yantri",
    username: "Yantri",
    s3_folder: "yantri/",
    img_qty: "9",
    img_ext: "png",
    countryCode: "bulgaria",
    links: [{
      web: "https://www.sotsf.net/",
      opensea: "https://opensea.io/accounts/Yantri",
      ig: "https://www.instagram.com/sotsf_art/",
      fb: "https://www.facebook.com/SeedsofTheStrangeForest",
      twitter: "https://twitter.com/Yantri19365241",
    },],
    titles: [{
      1: "Ablaze",
      2: "Fear",
      3: "Ladybird Woods",
      4: "Nyawu Forest",
      5: "Perpetul",
      6: "Phoenix",
      7: "The Bearer",
      8: "The Fire Spirit",
      9: "Transfix",
    }],
    bio:
      "Yantri is an illustrator and digital artist. He finished the Academy for Music, Dance and Fine Arts in Bulgaria. He worked as a graphic designer, but decided to draw his own ideas and is currently working on a comic and board game that share one universe.",
  },
  {
    name: "BrokeStarving NFTArtist",
    username: "BrokeStarving NFTArtist",
    s3_folder: "trojan/",
    img_qty: "4",
    img_ext: "png",
    countryCode: "malaysia",
    links: [{
      opensea: "https://opensea.io/accounts/BrokeStarvingNftArtist",
      twitter: "https://twitter.com/nftbroke",
      web: "https://oncyber.io/standard_deviant",
      hicetnunc: "https://www.hicetnunc.xyz/tz/tz1StR1fihf7MVBbfNem6eebwqijhpjT89cR",
      
    },],
    titles: [{
      1: "Boiler Room",
      2: "Dolphins",
      3: "Incarcerated Scarefaces",
      4: "Rainbow Eye",    
    }],
    bio:
      "Greetings my friends, NftBroke here to say I am grateful for the blessed oppertunity to create and collaborate and make a masterpiece out of our mayhem. Loving every moment of being in the space. It’s a blessing to create and create is what I do everyday; A lifelong artist in multi-disciplined mixed media of all sorts, from tattooing to the digital space, music and beats.",
  },
  {
    name: "Dominik Guembel",
    username: "DominikG",
    s3_folder: "domg/",
    img_qty: "7",
    img_ext: "jpg",
    countryCode: "germany",
    links: [{
      web: "https://dominikguembel.artstation.com/",
      twitter: "https://twitter.com/GuembelDominik",
      ig: "https://www.instagram.com/dominikguembel/",
      foundation: "https://foundation.app/dominikg",
      hicetnunc: "https://www.hicetnunc.xyz/tz/tz1X2LA9ZtjjZjZ86GTdgDM5sdBktbGjXqjF",
      
    },],
    titles: [{
      1: "1",
      2: "2",
      3: "3",
      4: "4",
      5: "5",
      6: "6",
      7: "7",

    }],
    bio:
      "Bold lines and vivid colors fueled by a retro synth fantasy.",
  },
  {
    name: "Aditya Sahay",
    username: "Aditya",
    s3_folder: "aditya/",
    img_qty: "4",
    img_ext: "png",
    countryCode: "india",
    links: [{
      twitter: "https://twitter.com/peppergum_",
      ig: "https://www.instagram.com/_adityasahay/",
      opensea: "https://opensea.io/accounts/Aditya_Sahay",
      hicetnunc: "https://t.co/WOOAEFJvnn?amp=1",

    },],
    titles: [{
      1: "Skull",
      2: "Dream Ave",
      3: "Gameboy",
      4: "Bright Sun",
    
    }],
    bio:
      "Hey, I'm Aditya, someone who loves making random stuff and having been doing digital art as hobby. I am always trying out new styles and love creating artworks. Hopefully you will like what I create.",
  },
  {
    name: "George Evangelista",
    username: "George Evangelista",
    s3_folder: "george/",
    img_qty: "12",
    img_ext: "jpg",
    countryCode: "australia",
    links: [{
      twitter: "https://twitter.com/artofgeorge",
      web: "https://artofgeorge.com/",
      ig: "https://www.instagram.com/georgeevangelista/",
      foundation: "https://foundation.app/georgeevangelista",
    },],
    titles: [{
      1: "Darkseid",
      2: "Darkwing Duck",
      3: "I Have the Power",
      4: "Classic Hulk",
      5: "Dead vs. Dredd",
      6: "Gargoyle",
      7: "Orcs on the Hunt",
      8: "Supermen",
      9: "Teela",
      10: "Batmen",
      11: "Webstor",
      12: "Wonder Woman",
    }],
    bio:
      "I'm a digital artist from Melbourne, Australia. I enjoy creating art based on nostalgic elements that I grew up with but also the pop culture we have today. I love digital art, 80s and 90s pop culture, superheroes, creatures and robots.",
  },
  {
    name: "Warren Magara",
    username: "Warren Magara",
    s3_folder: "magara/",
    img_qty: "10",
    img_ext: "png",
    countryCode: "kenya",
    links: [{
      web2: "https://www.amazon.com/Silva-Coalish-Gold-Links-Chronology-ebook/dp/B07YHW8Z6T/ref=sr_1_1?dchild=1&keywords=Silva+and+Coalish&qid=1621275335&sr=8-1",
      web: "https://www.webtoons.com/en/challenge/konrad-teddie/list?title_no=588966",
      ig: "https://www.instagram.com/warren_magara/",
    },],
    titles: [{
      1: "Jars",
      2: "Blue Forest",
      3: "Blue",
      4: "Espada",
      5: "Fishball",
      6: "Fubuki",
      7: "Senu",
      8: "Shackled",
      9: "Velma",
      10: "Woodland Spirit",
   }],
    bio:
      "Warren Magara is a 25-year-old Kenyan artist who specialises in graphic design. He has however strived to evade characterisation of his brand by experimenting with all sorts of mediums including but not limited to acrylic, 3D and ink. He has illustrated a webcomic named Konrad Teddie and published a fantasy novel named Silva and Coalish Gold.",
  },
  {
    name: "JL Mast",
    username: "JL Mast",
    s3_folder: "mast/",
    img_qty: "9",
    img_ext: "png",
    countryCode: "france",
    links: [{
      web2: "https://kuula.co/profile/jlmast",
      web: "http://mast360.com/index.php/en/home/",
      ig: "https://www.instagram.com/jl_mast/",
      twitter: "https://twitter.com/heymast",
      fb: "https://www.facebook.com/heymast/",
    },],
    titles: [{
      1: "Stan Lee",
      2: "Dakar, Senegal",
      3: "Doge Coin",
      4: "Joaquin Phoenix The Joker",
      5: "TMNT",
      6: "Spidey vs. Dock Ock",
      7: "Ziguinchor, Casamance",
      8: "Fathers of Marvel Comics",
      9: "Bignona, Senegal",
   }],
    bio:
      "JL Mast has worked on several Marvel Comics limited series: Daredevil/Punisher; Thanos; Avengers Age of Ultron Prelude; Ultimate Spider-Man; Guardians of the Galaxy. Current works include \"Fathers of Marvel Comics\", a huge Graphic Novel about the lives of Stan Lee & Martin Goodman, various VR Drawings and a VR Comic Book set in the Star Wars universe.",
  },
  {
    name: "Simeon Todorov",
    username: "Simeon Todorov",
    s3_folder: "todorov/",
    img_qty: "7",
    img_ext: "jpg",
    countryCode: "bulgaria",
    links: [{
      web: "https://www.artstation.com/simeontodorov",
      twitter: "https://twitter.com/SimeonTodorov14",
      fb: "https://www.facebook.com/simeon.todorov.1610/",
    },],
    titles: [{
      1: "Fantasy Forest",
      2: "Pirates in the Jungle",
      3: "Bone Valley",
      4: "Snowy Ruins",
      5: "Horse Mountains",
      6: "Summoning",
      7: "Fear Factory",
   }],
    bio:
      "Simeon is bulgarian junior concept artist currently trying to break into the game/movie industry. Studying graphic design, he found that his real passion is about movies and games. Now learning on his own, he tries to build a solid foundation and grow as an artist in this field.",
  },
  {
    name: "Joseph Diaz",
    username: "Joseph Diaz",
    s3_folder: "jdiaz/",
    img_qty: "9",
    img_ext: "jpg",
    countryCode: "spain",
    links: [{
      web: "https://www.artstation.com/josephdiaz",
      foundation: "https://foundation.app/josephdiaz",
      twitter: "https://twitter.com/jdiaz_art",
    },],
    titles: [{
      1: "Ready for War",
      2: "Dunwich Horror",
      3: "Horned Ronin",
      4: "Moonbeast",
      5: "Ronin Kamae",
      6: "The Memory Remains I",
      7: "The Memory Remains III",
      8: "The Memory Remains IV",
      9: "The Memory Remains V",
   }],
    bio:
      "Joseph Diaz is a digital artist with 15 years of experience in the entertainment industry. ADG nominated Art director/concept artist for Disney, Netflix, HBO, Game of Thrones, Lost in Space, Jungle Cruise, Warcraft, The Irregulars and a long etcetera.",
  },
  {
    name: "VVIZ",
    username: "VVIZ",
    s3_folder: "vviz/",
    img_qty: "12",
    img_ext: "png",
    countryCode: "cambodia",
    links: [{
      web: "https://vviz.carrd.co/",
      ig: "https://www.instagram.com/v.viz_/",
    },],
    titles: [{
      1: "The Search",
      2: "Cozy Interior",
      3: "A World to Explore",
      4: "Grass and Mountains",
      5: "New Age",
      6: "Sign of Life",
      7: "Sound of Nature",
      8: "The Forgotten Castle",
      9: "The Gathering",
      10: "The Remnant",
      11: "Victory",
      12: "View of a City",
   }],
    bio:
      "VVIZ is a concept artist and illustrator with 3 years of experience as a freelancer. His works are inspired by nature and technology. He loves to design new places that inviting the viewers to explore. His purpose is to create artworks that are never before seen but still relatable to the audience.",
  },
  {
    name: "Wacalac",
    username: "Wacalac",
    s3_folder: "wacalac/",
    img_qty: "10",
    img_ext: "jpg",
    countryCode: "new zealand",
    links: [{
      web: "https://www.artstation.com/wacalac",
      twitter: "https://twitter.com/wacalac_art",
      fb: "https://www.facebook.com/Wacalac",
      ig: "https://www.instagram.com/wacalac_art/",
    },],
    titles: [{
      1: "Dream",
      2: "Light",
      3: "Quiet Path",
      4: "Rising",
      5: "Waterfall",
      6: "Samurai",
      7: "The Shadow",
      8: "Jellyfish",
      9: "Patrol",
      10: "Awakening",
   }],
    bio:
      "Wacalac is a concept artist and illustrator based in New Zealand. Born in Thailand. Inspired by game art and old paintings he used those inspirations to help him paint his painterly fantasy digital paintings.",
  },
  {
    name: "Archangel",
    username: "Archangel",
    s3_folder: "archangel/",
    img_qty: "6",
    img_ext: "jpg",
    countryCode: "india",
    links: [{
      web: "https://www.archangel77.com/",
      twitter: "https://twitter.com/TheArchangel22",
      opensea: "https://opensea.io/accounts/TheArchangel",
      ig: "https://instagram.com/_thearchangel__/",
      foundation: "https://foundation.app/Archangel",
      rarible: "https://rarible.com/thearchangel77",
    },],
    titles: [{
      1: "Mortem",
      2: "Given and Denied",
      3: "Fallen",
      4: "Legend",
      5: "Defied",
      6: "The Veil",
   }],
    bio:
      "Hey, I'm Archangel, an abstract artist with strong affinity to hyper surrealism and occultism. I've been making digital artworks for 2 years with special focus on sculpting occult abstracts since October 2020, mostly specializing in gothic and dark, thus I try to simulate emotions in the form of dark, and derelict artworks.",
  },
  {
    name: "Dennis Mabuka",
    username: "Dennis Mabuka",
    s3_folder: "mabuka/",
    img_qty: "8",
    img_ext: "jpg",
    countryCode: "kenya",
    links: [{
      makers: "https://makersplace.com/riotgear/topshelf/",
      knownorigin: "https://knownorigin.io/riotgear",
      fb: "https://www.facebook.com/dennis.mose.73",
      ig: "https://www.instagram.com/riotgear3d/",
      twitter: "https://twitter.com/RIOTG3AR",
    },],
    titles: [{
      1: "Lawmaker",
      2: "Moneymaker",
      3: "Noisemaker",
      4: "Troublemaker",
      5: "Exfoliation",
      6: "Eyeballs",
      7: "Usurper",
      8: "Void",
   }],
    bio:
      "Dennis Mabuka is a 3d artist from Nairobi, Kenya. His work has been featured as a finalist in the largest car rendering challenge in the industry. He loves to work with music, credited with projects for west african artist Shatta Wale. His work loves to explore the mystical boundary between fantasy and sci-fi from the perspective of a mind developed in the east coast of Africa in the 20th & 21st century.",
  },
  ]
}

